eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: microservice-authentification
          uri: lb://microservice-authentification
          predicates:
            - Path=/authentification/**
          filters:
            - RewritePath=/authentification/(?<path>.*), /$\{path}
        
        - id: microservice-logement
          uri: lb://microservice-logement
          predicates:
            - Path=/logement/**
          filters:
            - RewritePath=/logement/(?<path>.*), /$\{path}
        
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
